In [1]:
import sklearn
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

In [2]:
import pandas as pd

iris = load_iris()

iris_data = iris.data   # 피처: 꽃받침의 너비, 길이, 꽃잎의 너비, 길이
iris_label = iris.target    # 아이리스 품종: 정답

print("iris target값:", iris_label)
print("iris target명:", iris.target_names)

iris target값: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
iris target명: ['setosa' 'versicolor' 'virginica']

In [3]:
iris.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.2],
       [5. , 3.2, 1.2, 0.2],
       [5.5, 3.5, 1.3, 0.2],
       [4.9, 3.6, 1.4, 0.1],
       [4.4, 3. , 1.3, 0.2],
       [5.1, 3.4, 1.5, 0.2],
       [5. , 3.5, 1.3, 0.3],
       [4.5, 2.3, 1.3, 0.3],
       [4.4, 3.2, 1.3, 0.2],
       [5. , 3.5, 1.6, 0.6],
       [5.1, 3.8, 1.9, 0.4],
       [4.8, 3. , 1.4, 0.3],
       [5.1, 3.8, 1.6, 0.2],
       [4.6, 3.2, 1.4, 0.2],
       [5.3, 3.7, 1.5, 0.2],
       [5. , 3.3, 1.4, 0.2],
       [7. , 3.2, 4.7, 1.4],
       [6.4, 3.2, 4.5, 1.5],
       [6.9, 3.1, 4.9, 1.5],
       [5.5, 2.3, 4. , 1.3],
       [6.5, 2.8, 4.6, 1.5],
       [5.7, 2.8, 4.5, 1.3],
       [6.3, 3.3, 4.7, 1.6],
       [4.9, 2.4, 3.3, 1. ],
       [6.6, 2.9, 4.6, 1.3],
       [5.2, 2.7, 3.9, 1.4],
       [5. , 2. , 3.5, 1. ],
       [5.9, 3. , 4.2, 1.5],
       [6. , 2.2, 4. , 1. ],
       [6.1, 2.9, 4.7, 1.4],
       [5.6, 2.9, 3.6, 1.3],
       [6.7, 3.1, 4.4, 1.4],
       [5.6, 3. , 4.5, 1.5],
       [5.8, 2.7, 4.1, 1. ],
       [6.2, 2.2, 4.5, 1.5],
       [5.6, 2.5, 3.9, 1.1],
       [5.9, 3.2, 4.8, 1.8],
       [6.1, 2.8, 4. , 1.3],
       [6.3, 2.5, 4.9, 1.5],
       [6.1, 2.8, 4.7, 1.2],
       [6.4, 2.9, 4.3, 1.3],
       [6.6, 3. , 4.4, 1.4],
       [6.8, 2.8, 4.8, 1.4],
       [6.7, 3. , 5. , 1.7],
       [6. , 2.9, 4.5, 1.5],
       [5.7, 2.6, 3.5, 1. ],
       [5.5, 2.4, 3.8, 1.1],
       [5.5, 2.4, 3.7, 1. ],
       [5.8, 2.7, 3.9, 1.2],
       [6. , 2.7, 5.1, 1.6],
       [5.4, 3. , 4.5, 1.5],
       [6. , 3.4, 4.5, 1.6],
       [6.7, 3.1, 4.7, 1.5],
       [6.3, 2.3, 4.4, 1.3],
       [5.6, 3. , 4.1, 1.3],
       [5.5, 2.5, 4. , 1.3],
       [5.5, 2.6, 4.4, 1.2],
       [6.1, 3. , 4.6, 1.4],
       [5.8, 2.6, 4. , 1.2],
       [5. , 2.3, 3.3, 1. ],
       [5.6, 2.7, 4.2, 1.3],
       [5.7, 3. , 4.2, 1.2],
       [5.7, 2.9, 4.2, 1.3],
       [6.2, 2.9, 4.3, 1.3],
       [5.1, 2.5, 3. , 1.1],
       [5.7, 2.8, 4.1, 1.3],
       [6.3, 3.3, 6. , 2.5],
       [5.8, 2.7, 5.1, 1.9],
       [7.1, 3. , 5.9, 2.1],
       [6.3, 2.9, 5.6, 1.8],
       [6.5, 3. , 5.8, 2.2],
       [7.6, 3. , 6.6, 2.1],
       [4.9, 2.5, 4.5, 1.7],
       [7.3, 2.9, 6.3, 1.8],
       [6.7, 2.5, 5.8, 1.8],
       [7.2, 3.6, 6.1, 2.5],
       [6.5, 3.2, 5.1, 2. ],
       [6.4, 2.7, 5.3, 1.9],
       [6.8, 3. , 5.5, 2.1],
       [5.7, 2.5, 5. , 2. ],
       [5.8, 2.8, 5.1, 2.4],
       [6.4, 3.2, 5.3, 2.3],
       [6.5, 3. , 5.5, 1.8],
       [7.7, 3.8, 6.7, 2.2],
       [7.7, 2.6, 6.9, 2.3],
       [6. , 2.2, 5. , 1.5],
       [6.9, 3.2, 5.7, 2.3],
       [5.6, 2.8, 4.9, 2. ],
       [7.7, 2.8, 6.7, 2. ],
       [6.3, 2.7, 4.9, 1.8],
       [6.7, 3.3, 5.7, 2.1],
       [7.2, 3.2, 6. , 1.8],
       [6.2, 2.8, 4.8, 1.8],
       [6.1, 3. , 4.9, 1.8],
       [6.4, 2.8, 5.6, 2.1],
       [7.2, 3. , 5.8, 1.6],
       [7.4, 2.8, 6.1, 1.9],
       [7.9, 3.8, 6.4, 2. ],
       [6.4, 2.8, 5.6, 2.2],
       [6.3, 2.8, 5.1, 1.5],
       [6.1, 2.6, 5.6, 1.4],
       [7.7, 3. , 6.1, 2.3],
       [6.3, 3.4, 5.6, 2.4],
       [6.4, 3.1, 5.5, 1.8],
       [6. , 3. , 4.8, 1.8],
       [6.9, 3.1, 5.4, 2.1],
       [6.7, 3.1, 5.6, 2.4],
       [6.9, 3.1, 5.1, 2.3],
       [5.8, 2.7, 5.1, 1.9],
       [6.8, 3.2, 5.9, 2.3],
       [6.7, 3.3, 5.7, 2.5],
       [6.7, 3. , 5.2, 2.3],
       [6.3, 2.5, 5. , 1.9],
       [6.5, 3. , 5.2, 2. ],
       [6.2, 3.4, 5.4, 2.3],
       [5.9, 3. , 5.1, 1.8]])

In [4]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [5]:
iris_df = pd.DataFrame(data = iris_data, columns = iris.feature_names)
iris_df["label"] = iris.target
iris_df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),label
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

In [6]:
# 학습셋과 테스트셋으로 나누기
X_train, X_test, y_train, y_test = train_test_split(iris_data, iris_label,
                                                     test_size = 0.2, random_state = 11)
# test_size = 0.2면 train_size는 0.8

In [7]:
dt_clf = DecisionTreeClassifier(random_state = 11)  # 결정트리 클래스 객체 생성

In [8]:
dt_clf.fit(X_train, y_train)    # X_train, y_train 값을 dt_clf에 할당

DecisionTreeClassifier(random_state=11)

In [9]:
pred = dt_clf.predict(X_test)

In [10]:
pred

array([2, 2, 1, 1, 2, 0, 1, 0, 0, 1, 1, 1, 1, 2, 2, 0, 2, 1, 2, 2, 1, 0,
       0, 1, 0, 0, 2, 1, 0, 1])

In [11]:
from sklearn.metrics import accuracy_score
print("예측 정확도: ", accuracy_score(y_test, pred))

예측 정확도:  0.9333333333333333

In [12]:
from sklearn.model_selection import KFold
import numpy as np

kfold = KFold(n_splits = 5)     # 데이터 값을 5개로 나눔
cv_accuracy = []

In [ ]:
n_iter = 0
features = iris.data
label = iris.target

for train_index, test_index in kfold.split(features):               # iris.data를 kfold로 나눔
    X_train, X_test = features[train_index], features[test_index]   # 학습 데이터와 검증 데이터 값을 X_train, X_test에 할당
    y_train, y_test = label[train_index], label[test_index]         # label 값을 y_train, y_test에 할당

    dt_clf.fit(X_train, y_train)                                    # 학습 데이터와 검증 데이터 값 df_clf에 할당
    pred = dt_clf.predict(X_test)
    n_iter += 1                                                     

    accuracy = np.round(accuracy_score(y_test, pred), 4)            # accuracy 값을 소수점 4자리까지 출력
    train_size = X_train.shape[0]                                   # 학습 데이터 행 개수 확인
    test_size = X_test.shape[0]                                     # 검증 데이터 행 개수 확인
    print(n_iter)
    print("교차검증 정확도: ", accuracy)
    print("학습 데이터 크기: ", train_size)
    print("검증 데이터 크기: ", test_size)
    cv_accuracy.append(accuracy)

print("평균 정확도: ", np.mean(cv_accuracy))

1
교차검증 정확도:  1.0
학습 데이터 크기:  120
검증 데이터 크기:  30
2
교차검증 정확도:  0.9667
학습 데이터 크기:  120
검증 데이터 크기:  30
3
교차검증 정확도:  0.8667
학습 데이터 크기:  120
검증 데이터 크기:  30
4
교차검증 정확도:  0.9333
학습 데이터 크기:  120
검증 데이터 크기:  30
5
교차검증 정확도:  0.8333
학습 데이터 크기:  120
검증 데이터 크기:  30
평균 정확도:  0.9200000000000002

In [14]:
iris_df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),label
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

In [15]:
iris_df["label"].value_counts()

0    50
1    50
2    50
Name: label, dtype: int64

In [ ]:
kfold = KFold(n_splits=3)   # KFold를 3개로 나눔
n_iter = 0

for train_index, test_index in kfold.split(iris_df):    # iris_df 데이터를 kfold로 나눔
    n_iter += 1
    label_train = iris_df["label"].iloc[train_index]    # 학습 인덱스로 label 가져옴
    label_test = iris_df["label"].iloc[test_index]      # 검증 인덱스로 label 가져옴
    print("학습 레이블 데이터 분포: ", label_train.value_counts())
    print("검증 레이블 데이터 분포: ", label_test.value_counts())

학습 레이블 데이터 분포:  1    50
2    50
Name: label, dtype: int64
검증 레이블 데이터 분포:  0    50
Name: label, dtype: int64
학습 레이블 데이터 분포:  0    50
2    50
Name: label, dtype: int64
검증 레이블 데이터 분포:  1    50
Name: label, dtype: int64
학습 레이블 데이터 분포:  0    50
1    50
Name: label, dtype: int64
검증 레이블 데이터 분포:  2    50
Name: label, dtype: int64

In [ ]:
from sklearn.model_selection import StratifiedKFold

skf = StratifiedKFold(n_splits = 3) # 데이터를 3개로 나눔
n_iter = 0

for train_index, test_index in skf.split(iris_df, iris_df["label"]):    # iris_df를 학습 인덱스와 검증 인덱스로 나눔
    n_iter += 1 
    label_train = iris_df["label"].iloc[train_index]
    label_test = iris_df["label"].iloc[test_index]
    print("학습 레이블 데이터 분포: ", label_train.value_counts())  # 학습 인덱스로 label 가져옴
    print("검증 레이블 데이터 분포: ", label_test.value_counts())   # 검증 인덱스로 label 가져옴

학습 레이블 데이터 분포:  2    34
0    33
1    33
Name: label, dtype: int64
검증 레이블 데이터 분포:  0    17
1    17
2    16
Name: label, dtype: int64
학습 레이블 데이터 분포:  1    34
0    33
2    33
Name: label, dtype: int64
검증 레이블 데이터 분포:  0    17
2    17
1    16
Name: label, dtype: int64
학습 레이블 데이터 분포:  0    34
1    33
2    33
Name: label, dtype: int64
검증 레이블 데이터 분포:  1    17
2    17
0    16
Name: label, dtype: int64

In [ ]:
df_clf = DecisionTreeClassifier(random_state = 156) # 의사 결정트리 모델 생성
skfold = StratifiedKFold(n_splits = 3)  # 데이터를 3개로 나눔
n_iter = 0
cv_accuracy = []

for train_index, test_index in skfold.split(features, label):   # features와 label을 이용해 학습 인덱스와 검증 인덱스로 나눔
    X_train, X_test = features[train_index], features[test_index]   # 학습 인덱스와 검증 인덱스를 이용해 X_train, X_test를 나눔
    y_train, y_test = label[train_index], label[test_index]         # 학습 인덱스와 검증 인덱스를 ㅇ용해 y_train, y_test를 나눔
    df_clf.fit(X_train, y_train)
    pred = df_clf.predict(X_test)

    n_iter += 1
    accuracy = np.round(accuracy_score(y_test, pred), 4)        # 소수점 4자리까지 출력
    cv_accuracy.append(accuracy)

print("평균 검증 정확도: ", np.round(np.mean(cv_accuracy), 4))      # 소수점 4자리까지 출력

평균 검증 정확도:  0.9667

In [ ]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(dt_clf, features, label, scoring = "accuracy", cv = 3) # 데이터를 3개로 나눔
print("교차 검증별 정확도: ", np.round(scores, 4))  # 소수점 4자리까지 출력
print("평균 검증별 정확도:", np.round(np.mean(scores), 4))  # 소수점 4자리까지 출력

교차 검증별 정확도:  [0.98 0.92 0.98]
평균 검증별 정확도: 0.96

In [ ]:
from sklearn.model_selection import GridSearchCV
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target,
                                                   test_size = 0.2, random_state = 121) # test_size = 0.2면 train_size는 0.8

parameters = {"max_depth": [1, 2, 3], "min_samples_split": [2, 3]}

In [21]:
dtree = DecisionTreeClassifier()

grid_dtree = GridSearchCV(dtree, param_grid = parameters, cv = 3, refit = True)
grid_dtree.fit(X_train, y_train)
scores_df = pd.DataFrame(grid_dtree.cv_results_)
scores_df[["params", "mean_test_score", "rank_test_score", "split0_test_score", "split1_test_score", "split2_test_score"]]

,params,mean_test_score,rank_test_score,split0_test_score,split1_test_score,split2_test_score
0,"{'max_depth': 1, 'min_samples_split': 2}",0.700000,5,0.700,0.7,0.70
1,"{'max_depth': 1, 'min_samples_split': 3}",0.700000,5,0.700,0.7,0.70
2,"{'max_depth': 2, 'min_samples_split': 2}",0.958333,3,0.925,1.0,0.95
3,"{'max_depth': 2, 'min_samples_split': 3}",0.958333,3,0.925,1.0,0.95
4,"{'max_depth': 3, 'min_samples_split': 2}",0.975000,1,0.975,1.0,0.95
5,"{'max_depth': 3, 'min_samples_split': 3}",0.975000,1,0.975,1.0,0.95

In [22]:
grid_dtree.best_params_

{'max_depth': 3, 'min_samples_split': 2}

In [23]:
grid_dtree.best_score_

0.975

In [24]:
estimator = grid_dtree.best_estimator_

pred = estimator.predict(X_test)
print(accuracy_score(y_test, pred))

0.9666666666666667

In [ ]:
from sklearn.preprocessing import LabelEncoder 

items = ["TV", "냉장고", "전자레인지", "컴퓨터", "선풍기", "선풍기", "믹서", "믹서"]

encoder = LabelEncoder() # encodr 생성
encoder.fit(items)
labels = encoder.transform(items)   # items 데이터를 숫자로 변환
print(labels)

[0 1 4 5 3 3 2 2]

In [26]:
encoder.classes_

array(['TV', '냉장고', '믹서', '선풍기', '전자레인지', '컴퓨터'], dtype='<U5')

In [ ]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

items = ["TV", "냉장고", "전자레인지", "컴퓨터", "선풍기", "선풍기", "믹서", "믹서"]

items = np.array(items).reshape(-1, 1)  # 2차원 배열로 생성
items

array([['TV'],
       ['냉장고'],
       ['전자레인지'],
       ['컴퓨터'],
       ['선풍기'],
       ['선풍기'],
       ['믹서'],
       ['믹서']], dtype='<U5')

In [28]:
oh_encoder = OneHotEncoder()
oh_encoder.fit(items)
oh_labels = oh_encoder.transform(items)

print(oh_labels.toarray())
print(oh_labels.shape)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
(8, 6)

In [29]:
df = pd.DataFrame({"items" : ["TV", "냉장고", "전자레인지", "컴퓨터", "선풍기", "선풍기", "믹서", "믹서"]})
df.head()

   items
0     TV
1    냉장고
2  전자레인지
3    컴퓨터
4    선풍기

In [30]:
pd.get_dummies(df)

   items_TV  items_냉장고  items_믹서  items_선풍기  items_전자레인지  items_컴퓨터
0         1          0         0          0            0          0
1         0          1         0          0            0          0
2         0          0         0          0            1          0
3         0          0         0          0            0          1
4         0          0         0          1            0          0
5         0          0         0          1            0          0
6         0          0         1          0            0          0
7         0          0         1          0            0          0

In [ ]:
from sklearn.datasets import load_iris

iris = load_iris()
iris_data = iris.data   # 데이터 저장
iris_df = pd.DataFrame(data = iris_data, columns = iris.feature_names)  # 데이터 프레임 생성

print(iris_df.mean())
print(iris_df.var())

sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64
sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler() # 스케일러 생성
scaler.fit(iris_df) # 데이터 평균과 표준편차 학습
iris_scaled = scaler.transform(iris_df) # 데이터 표준화

iris_df_scaled = pd.DataFrame(data = iris_scaled, columns = iris.feature_names) # 데이터 프레임 생성
print(iris_df_scaled.mean())
print(iris_df_scaled.var())

sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64
sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64

In [ ]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler() # 스케일러 생성
scaler.fit(iris_df) # 데이터, 최솟값, 최댓값 학습
iris_scaled = scaler.transform(iris_df) # 데이터를 0~1 범위로 변환

iris_df_scaled = pd.DataFrame(data = iris_scaled, columns = iris.feature_names) # 데이터 프레임 생성
print(iris_df_scaled.min())
print(iris_df_scaled.max())

sepal length (cm)    0.0
sepal width (cm)     0.0
petal length (cm)    0.0
petal width (cm)     0.0
dtype: float64
sepal length (cm)    1.0
sepal width (cm)     1.0
petal length (cm)    1.0
petal width (cm)     1.0
dtype: float64